events {}
http {
    include mime.types;
    types {
        application/wasm wasm;
        application/javascript js;
    }
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location /_framework/ {
            try_files $uri =404;
            add_header Cache-Control "no-cache";
            add_header Cross-Origin-Opener-Policy "same-origin";
            add_header Cross-Origin-Embedder-Policy "require-corp";
        }

        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache";
        }
    }
}